# Generated by Django 3.2.2 on 2021-05-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbBackup', '0002_alter_post_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
